name: Build and test
on: [pull_request, push]

jobs:
  build-n-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ada-toml
      uses: actions/checkout@master
      with:
        path: ada-toml

    - name: Checkout gnatcoll-core
      uses: actions/checkout@master
      with:
        repository: AdaCore/gnatcoll-core
        path: gnatcoll-core

    - name: Cache gnatcoll-core/alire
      uses: actions/cache@v4
      with:
        key: gnatcoll-core-alire
        path: gnatcoll-core/alire

    - name: Set up Alire
      uses: alire-project/setup-alire@v4

    - name: Install Python 3.x
      uses: actions/setup-python@master
      with:
        python-version: '3.12'

    - name: Build gnatcoll
      run: |
        cd gnatcoll-core
        alr -n build
        alr -n -q printenv >> ../env

    - name: Build ada-toml
      run: |
        . ./env
        gprbuild -Pada-toml/ada_toml.gpr -p -j0

    - name: Build test programs
      run: |
        . ./env
        gprbuild -Pada-toml/checkers.gpr -p -j0

    - name: Install e3-testsuite
      run: pip install e3-testsuite

    - name: Run the testsuite
      run: ./run-tests.py
